### ISSUE TITLE
Progress Reports cutting off

### ISSUE THREAD

**Issue by mdewey** [suncoast-devs/nexus#17]
problem: 
``` the Progress Report seems to be cut off on the right margin. Also, it seems to be an image, so I can't mark the text in an attempt to get to the off-screen portion.
```
![Progress Report](https://user-images.githubusercontent.com/1793923/68805788-7fc57580-0632-11ea-926c-b2666f168b93.jpg)

It looks like the image that is being produced is cutting off the right margin.

**Comment by gstark** [comment]
This layout has been changed and this is no longer applicable
