### ISSUE TITLE
Re-open Assignment issue

### ISSUE THREAD

**Issue by mdewey** [suncoast-devs/nexus#4]
Problem: 
A student has submitted homework that still needs work. The user grading homework needs a way to re-open the issue to let the student know they need more work. 

Desired behavior:
When the user clicks "unacceptable", nexus should reopen the Github issue.

**Comment by gstark** [comment]
Now if you rate a homework `UNACCEPTABLE` or `NEEDS_IMPROVEMENT` - it will reopen the issue. If we don't want `NEEDS_IMPROVEMENT` to reopen the issue we can change this.

**Comment by gstark** [comment]
@mdewey Please close if this now works and is acceptable.
