### ISSUE TITLE
Gradebook does not tell the % of assignments completed

### ISSUE THREAD

**Issue by ktrammell95** [suncoast-devs/nexus#6]
The old grading app used to have the % completed for homework and this was a very helpful tool.

![Screen Shot 2019-08-19 at 4 33 47 PM](https://user-images.githubusercontent.com/10440779/63297321-23ef8880-c29f-11e9-9b15-0a61bc6f1531.png)

**Comment by gstark** [comment]
Now the gradebook shows the total # of assignments that count towards completion and a percentage for each student.

The computation adds up each assignment for a student if it counts AND if the student's score is ACCEPTABLE or higher.

We then show the percentage to one fixed decimal place and color code it green/red based on a comparison to 80% -- *NOTE* This requires the assignments to be graded to factor into the computation.

I could add a second computation with the assumption that any ungraded assignment would be considered acceptable as this might give a better picture in the case where we are behind on grading assignments.

Another idea is that we could sort this table by completion %
