### ISSUE TITLE
Download progress reports

### ISSUE THREAD

**Issue by ktrammell95** [suncoast-devs/nexus#7]
Need the ability to download the progress reports so they can be saved in the student's record.

**Comment by gstark** [comment]
Can we allow nexus to be the official student record for attendance and progress reports?

I can add a "download" button for each individual student progress report as well as looking into making a "download all" that would generate a zip file to download.

**Comment by gstark** [comment]
There is now a download link for each student's progress report.

I may still look at providing a single overall download button to download an archive of all the student progress reports.

![Nexus 2019-09-25 14-40-33](https://user-images.githubusercontent.com/2607/65629954-714bcd80-dfa2-11e9-87a0-b2ca1935a753.png)
