### ISSUE TITLE
Assignments are going missing

### ISSUE THREAD

**Issue by mdewey** [suncoast-devs/nexus#9]
Issue: 
As I was making and assigning new homework assignments, only the 30 most recent assignments are showing and the early assignment completion statuses are not showing. The issue is still there in github, but the completion status is not showing 

<img width="1042" alt="Screen Shot 2019-09-24 at 4 21 11 PM" src="https://user-images.githubusercontent.com/1793923/65547394-6718c900-dee7-11e9-8661-ed59a3b3628b.png">

**Comment by gstark** [comment]
Changed pylon to automatically paginate through results from github, essentially fetching all data in the GithubIssueInterface class
